# ОСНОВНАЯ КОНФИГУРАЦИЯ
tproxy-port: 1181
socks-port: 1080
allow-lan: true
find-process-mode: 'off'
mode: rule
log-level: silent
ipv6: false
external-controller: '0.0.0.0:9090'
unified-delay: true
tcp-concurrent: true

geox-url:
  geosite: 'https://github.com/jameszeroX/zkeen-domains/releases/latest/download/zkeen.dat'
  geoip: 'https://github.com/jameszeroX/zkeen-ip/releases/latest/download/zkeenip.dat'
geo-auto-update: true
geo-update-interval: 72
geodata-mode: true

global-client-fingerprint: firefox
external-ui: './zashboard'
external-ui-url: 'https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip'
profile: { store-selected: true }

sniffer: { enable: true, force-dns-mapping: true, parse-pure-ip: true, sniff: { HTTP: {}, TLS: {}, QUIC: {} } }

# ЯКОРЯ
anchors:
  a1: &provider-template { health-check: {enable: true, url: 'http://www.gstatic.com/generate_204', interval: 300, timeout: 8000, lazy: true, expected-status: 204}, override: {tfo: true, mptcp: true, udp: true}, interval: 3600 }
  a2: &group-template { url: 'http://www.gstatic.com/generate_204', interval: 60, lazy: true }
  a3: &domain { type: http, format: mrs, behavior: domain, interval: 86400 }
#  a4: &ipcidr { type: http, format: mrs, behavior: ipcidr, interval: 86400 }
#  a5: &classical { type: http, format: text, behavior: classical, interval: 86400 }
#  a6: &inline { type: inline, behavior: classical }

proxies:
  - { name: '🇪🇪 AMNEZIA', icon: 'https://amnezia.org/img/logos/logo-a-sym.svg', type: direct, interface-name: 'nwg0' }

proxy-providers:
  EE_sub: { <<: *provider-template, type: http, url: 'ВАША ПОДПИСКА' }
  DE_sub: { <<: *provider-template, type: http, url: 'ВАША ПОДПИСКА' }

proxy-groups:
  - { name: 'PROXY FASTEST', <<: *group-template, icon: 'https://cdn-icons-png.flaticon.com/512/1455/1455324.png', type: url-test, use: ['EE_sub','DE_sub'], proxies: ['🇪🇪 AMNEZIA'], tolerance: 50 }
  - { name: 'PROXY FAILOVER', <<: *group-template, icon: 'https://i.ibb.co/5hR4KYXy/server-failover.png', type: fallback, proxies: ['🇪🇪 AMNEZIA','PROXY FASTEST','DIRECT'], max-allowed-delay: 300 }
  - { name: 'VLESS PROXY', <<: *group-template, icon: 'https://i.ibb.co/WWd9j19V/18240592.png', type: url-test, use: ['EE_sub','DE_sub'], interval: 300, tolerance: 50 }
  - { name: 'YOUTUBE', icon: 'https://cdn-icons-png.flaticon.com/512/270/270834.png', type: select, proxies: ['DIRECT','PROXY FAILOVER'] }
  - { name: 'ADS BLOCK', icon: 'https://i.ibb.co/ymfqTJ3c/NO-ADSSS.png', type: select, proxies: ['REJECT','DIRECT'] }
  - { name: 'OTHER', icon: 'https://i.ibb.co/bMW500kb/notification-icon-meta-logo-icon-size-512.png', type: select, proxies: ['DIRECT','PROXY FAILOVER'] }
  - { name: 'AI', type: select, icon: 'https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Bot.png', proxies: ['VLESS PROXY', 'DIRECT'] }
  - { name: 'QUIC', type: select, icon: 'https://github.com/zxc-rv/assets/raw/main/group-icons/quic.png', proxies: ['REJECT', 'DIRECT'] }

rule-providers:
  category-ai@domain: { <<: *domain, url: 'https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/category-ai-!cn.mrs' }
#  SMART_TV_BLOCK: { <<: *classical, url: 'https://raw.githubusercontent.com/hkamran80/blocklists/main/smart-tv.txt' }
#  HAGEZI_PRO: { <<: *domain, url: 'https://github.com/zxc-rv/ad-filter/releases/latest/download/adlist.mrs' }
#  OISD_BIG: { <<: *domain, url: "https://github.com/legiz-ru/mihomo-rule-sets/raw/main/oisd/big.mrs" }

rules:
  # ЗАПРЕЩАЮЩИЕ ПРАВИЛА (REJECT / ADS BLOCK)
  # Блокировка UDP-трафика на 443 порт с нероссийских IP (анти-QUIC)
  - 'AND,((NETWORK,UDP),(DST-PORT,443),(GEOIP,!RU)),QUIC'

  # БЛОКИРОВКА | РЕКЛАМА И ДР.
  # - 'RULE-SET,SMART_TV_BLOCK,ADS BLOCK'
  # - 'RULE-SET,HAGEZI_PRO,ADS BLOCK'
  # - 'RULE-SET,OISD_BIG,ADS BLOCK'
  - 'DOMAIN-SUFFIX,tracking.ott.yandex.net,ADS BLOCK'
  - 'DOMAIN-SUFFIX,egress.yandex.net,ADS BLOCK'
  - 'DOMAIN-SUFFIX,loveplanet.ru,ADS BLOCK'
  - 'DOMAIN-SUFFIX,mamba.ru,ADS BLOCK'

  # ПРАВИЛА, ИДУЩИЕ НАПРЯМУЮ (DIRECT)
  # Исключения | Разное
  - 'DOMAIN,2ip.ru,DIRECT' # размещен за cloudflauer
  - 'DOMAIN-SUFFIX,tv.ott.net.ru,DIRECT' # IPTV LIGHT
  - 'DOMAIN-SUFFIX,only4.tv,DIRECT' # IPTV 1CENT
  - 'DOMAIN-SUFFIX,rt-ct-vrzh-htlive.cdn.ngenix.net,DIRECT' # IPTV RT
  # TV.TEAM (потоки и speedtest)
  - 'DOMAIN-SUFFIX,tv.in,DIRECT'
  - 'DOMAIN-SUFFIX,speed.tv.team,DIRECT'
  - 'DOMAIN-SUFFIX,team.ga,DIRECT'
  - 'DOMAIN-SUFFIX,troya.info,DIRECT'

  # ИИ
  - 'RULE-SET,category-ai@domain,AI'

  # ПРОКСИРУЕМЫЕ ДОМЕНЫ
  - 'GEOSITE,DOMAINS,PROXY FAILOVER'
  - 'GEOSITE,OTHER,PROXY FAILOVER'
  - 'GEOSITE,POLITIC,PROXY FAILOVER'
  # - 'GEOSITE,YOUTUBE,PROXY FAILOVER'
  - 'GEOSITE,YOUTUBE,YOUTUBE'

  # ПРОКСИРУЕМЫЕ IP
  - 'GEOIP,AKAMAI,PROXY FAILOVER'
  - 'GEOIP,AMAZON,PROXY FAILOVER'
  - 'GEOIP,CDN77,PROXY FAILOVER'
  - 'GEOIP,COLOCROSSING,PROXY FAILOVER'
  - 'GEOIP,CONTABO,PROXY FAILOVER'
  - 'GEOIP,CLOUDFLARE,PROXY FAILOVER'
  - 'GEOIP,DIGITALOCEAN,PROXY FAILOVER'
  - 'GEOIP,DISCORD,PROXY FAILOVER' # VLESS PROXY' 
  - 'GEOIP,FASTLY,PROXY FAILOVER'
  - 'GEOIP,GCORE,PROXY FAILOVER'
  # - 'GEOIP,GOOGLE,PROXY FAILOVER'
  - 'GEOIP,HETZNER,PROXY FAILOVER'
  - 'GEOIP,LINODE,PROXY FAILOVER'
  - 'GEOIP,MEGA,PROXY FAILOVER'
  - 'GEOIP,META,VLESS PROXY' # PROXY FAILOVER'
  - 'GEOIP,ORACLE,PROXY FAILOVER'
  - 'GEOIP,OVH,PROXY FAILOVER'
  - 'GEOIP,SCALEWAY,PROXY FAILOVER'
  - 'GEOIP,TELEGRAM,PROXY FAILOVER'
  - 'GEOIP,VULTR,PROXY FAILOVER'
  # - 'GEOIP,YOUTUBE,PROXY FAILOVER'

  # ДОПОЛНИТЕЛЬНЫЕ ПРАВИЛА
  # РАЗНОЕ
  - 'DOMAIN-SUFFIX,ottbill.cc,PROXY FAILOVER'
  - 'DOMAIN,sharavoz.space,PROXY FAILOVER'
  - 'DOMAIN-SUFFIX,myip.com,PROXY FAILOVER'
  - 'DOMAIN-SUFFIX,2ip.io,PROXY FAILOVER'
  - 'DOMAIN-SUFFIX,ipwhois.app,PROXY FAILOVER'
  - 'DOMAIN-SUFFIX,ipwho.is,PROXY FAILOVER'
  - 'DOMAIN-SUFFIX,ip.sb,PROXY FAILOVER'
  # - 'DOMAIN-SUFFIX,ipapi.co,PROXY FAILOVER'
  - 'DOMAIN-SUFFIX,files.catbox.moe,PROXY FAILOVER'
  - 'DOMAIN-SUFFIX,warpgen.net,PROXY FAILOVER'
  - 'DOMAIN,rutor.org,PROXY FAILOVER'
  - 'DOMAIN,dns.sb,PROXY FAILOVER'
  - 'DOMAIN-SUFFIX,kira.art,PROXY FAILOVER' # AI PHOTOSHOP
  - 'DOMAIN-SUFFIX,ottclub.tv,PROXY FAILOVER'
  - 'DOMAIN-SUFFIX,dreamerscast.com,PROXY FAILOVER'
  - 'DOMAIN-SUFFIX,tlauncher.ru,PROXY FAILOVER'
  - 'DOMAIN-SUFFIX,justpaste.it,PROXY FAILOVER'

  # VIVOX / Phasmophobia Voice Chat
  - 'DOMAIN-KEYWORD,vivox,PROXY FAILOVER'
  - 'IP-CIDR,85.236.96.0/21,PROXY FAILOVER'

  # Riot Games / League of Legends
  - 'IP-CIDR,104.160.128.0/19,PROXY FAILOVER'
  - 'IP-CIDR,185.40.64.0/22,PROXY FAILOVER'
  - 'IP-CIDR,151.106.240.0/20,PROXY FAILOVER'
  - 'IP-CIDR,192.64.168.0/21,PROXY FAILOVER'
  - 'IP-CIDR,162.249.72.0/21,PROXY FAILOVER'
  - 'IP-CIDR,103.219.128.0/22,PROXY FAILOVER'
  - 'IP-CIDR,103.240.224.0/22,PROXY FAILOVER'
  - 'IP-CIDR,43.229.64.0/22,PROXY FAILOVER'
  - 'IP-CIDR,45.250.208.0/22,PROXY FAILOVER'
  - 'IP-CIDR,45.7.36.0/22,PROXY FAILOVER'
  - 'IP-CIDR,138.0.12.0/23,PROXY FAILOVER'
  - 'IP-CIDR,151.106.250.0/23,PROXY FAILOVER'
  - 'IP-CIDR,192.207.0.0/24,PROXY FAILOVER'
  - 'IP-CIDR,104.160.141.3/32,PROXY FAILOVER'
  - 'IP-CIDR,104.160.142.3/32,PROXY FAILOVER'
  - 'IP-CIDR,104.160.131.3/32,PROXY FAILOVER'
  - 'IP-CIDR,104.160.156.1/32,PROXY FAILOVER'
  - 'IP-CIDR,104.160.152.3/32,PROXY FAILOVER'
  - 'IP-CIDR,185.40.67.1/32,PROXY FAILOVER'
  - 'IP-CIDR,104.160.131.0/24,PROXY FAILOVER'
  - 'IP-CIDR,172.65.212.0/24,PROXY FAILOVER'

  # ЗАВЕРШАЮЩЕЕ ПРАВИЛО
  - 'MATCH,OTHER'
