tproxy-port: 1181
mixed-port: 1080

# лЮлљлАлблалълЎлџлў л»лћлалљ
allow-lan: true
find-process-mode: 'off'
mode: rule
geox-url:
  geosite: 'https://github.com/v2fly/domain-list-community/releases/latest/download/dlc.dat'
  geoip: 'https://github.com/MetaCubeX/meta-rules-dat/releases/latest/download/geoip.dat'
  mmdb: 'https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.metadb'
geo-auto-update: true
geo-update-interval: 24
# geodata-mode: true # л▓лЙлил╝лЙлХлйЛІлх лилйл░ЛЄлхлйлИЛЈ: true/false, true л┤л╗ЛЈ dat, л┐лЙ ЛЃл╝лЙл╗ЛЄл░лйлИЛј false
log-level: silent
ipv6: false
external-controller: 0.0.0.0:9090
tcp-concurrent: true
external-ui: ./zashboard
external-ui-url: 'https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip'
profile:
  store-selected: true

# лЮлљлАлблалълЎлџлў лАлЮлўлцлцлЋлалљ
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  sniff:
    QUIC:
      ports: [443]
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
  skip-domain:
    - '+.telegram.org'

# лАлЪлўлАлълџ лЪлалълџлАлў лАлЋлалњлЋлалълњ
proxies:
  - name: '­ЪЄф­ЪЄф лАлЋлалњлЋла'
    icon: 'https://www.svgrepo.com/download/365909/estonia.svg'
    type: vless
    server: YOUR
    port: 443
    uuid: YOUR
    network: ws
    tls: true
    servername: YOUR
    skip-cert-verify: true
    client-fingerprint: chrome
    udp: true
    ws-opts:
      path: YOUR
  - name: '­ЪЄЕ­ЪЄф лАлЋлалњлЋла'
    icon: 'https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Germany.png'
    type: vless
    server: YOUR
    port: 443
    uuid: YOUR
    network: ws
    tls: true
    servername: YOUR
    skip-cert-verify: true
    client-fingerprint: chrome
    udp: true
    ws-opts:
      path: YOUR

# лАлЪлўлАлълџ лЪлалълџлАлў лЊлалБлЪлЪ
proxy-groups:
  - name: 'лблБлалЉлъ ­Ъџђ'
    icon: 'https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/European_Union.png'
    type: url-test
    proxies:
      - '­ЪЄф­ЪЄф лАлЋлалњлЋла'
      - '­ЪЄЕ­ЪЄф лАлЋлалњлЋла'
    url: 'http://www.msftncsi.com/ncsi.txt'
    interval: 60
    lazy: true
    tolerance: 50

  - name: 'лблЋлџлБлЕлўлЎ ­ЪќЦ'
    icon: 'https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Rocket.png'
    type: fallback
    proxies:
      - 'лблБлалЉлъ ­Ъџђ'
      - 'DIRECT'
    url: 'http://www.msftncsi.com/ncsi.txt'
    interval: 60
    lazy: true

  - name: 'GEMINI РЎі'
    type: select
    proxies:
      - 'лблЋлџлБлЕлўлЎ ­ЪќЦ'
      - '­ЪЄф­ЪЄф лАлЋлалњлЋла'
      - '­ЪЄЕ­ЪЄф лАлЋлалњлЋла'
      - 'DIRECT'
    icon: 'https://www.svgrepo.com/show/331406/gemini.svg'

  - name: 'SPOTIFY ­ЪјД'
    type: select
    proxies:
      - 'лблЋлџлБлЕлўлЎ ­ЪќЦ'
      - '­ЪЄф­ЪЄф лАлЋлалњлЋла'
      - '­ЪЄЕ­ЪЄф лАлЋлалњлЋла'
      - 'DIRECT'
    icon: 'https://www.svgrepo.com/show/349511/spotify.svg'

  - name: 'DISCORD ­Ъњг'
    type: select
    proxies:
      - 'лблЋлџлБлЕлўлЎ ­ЪќЦ'
      - '­ЪЄф­ЪЄф лАлЋлалњлЋла'
      - '­ЪЄЕ­ЪЄф лАлЋлалњлЋла'
      - 'DIRECT'
    icon: 'https://www.svgrepo.com/show/353655/discord-icon.svg'

  - name: 'WHATSAPP ­ЪЊ▒'
    type: select
    proxies:
      - 'лблЋлџлБлЕлўлЎ ­ЪќЦ'
      - '­ЪЄф­ЪЄф лАлЋлалњлЋла'
      - '­ЪЄЕ­ЪЄф лАлЋлалњлЋла'
      - 'DIRECT'
    icon: 'https://www.svgrepo.com/show/303147/whatsapp-icon-logo.svg'

  - name: 'NETFLIX ­Ъјг'
    type: select
    proxies:
      - 'лблЋлџлБлЕлўлЎ ­ЪќЦ'
      - '­ЪЄф­ЪЄф лАлЋлалњлЋла'
      - '­ЪЄЕ­ЪЄф лАлЋлалњлЋла'
      - 'DIRECT'
    icon: 'https://www.svgrepo.com/show/303341/netflix-1-logo.svg'

  - name: '2IP.IO ­ЪЊЇ'
    type: select
    proxies:
      - 'лблЋлџлБлЕлўлЎ ­ЪќЦ'
      - '­ЪЄф­ЪЄф лАлЋлалњлЋла'
      - '­ЪЄЕ­ЪЄф лАлЋлалњлЋла'
      - 'DIRECT'
    icon: 'https://www.svgrepo.com/show/415672/address-location-map.svg'

  - name: 'TWITTER ­Ъљд'
    type: select
    proxies:
      - 'лблЋлџлБлЕлўлЎ ­ЪќЦ'
      - '­ЪЄф­ЪЄф лАлЋлалњлЋла'
      - '­ЪЄЕ­ЪЄф лАлЋлалњлЋла'
      - 'DIRECT'
    icon: 'https://www.svgrepo.com/show/452121/twitter-1.svg'

  - name: 'INSTAGRAM ­ЪЊИ'
    type: select
    proxies:
      - 'лблЋлџлБлЕлўлЎ ­ЪќЦ'
      - '­ЪЄф­ЪЄф лАлЋлалњлЋла'
      - '­ЪЄЕ­ЪЄф лАлЋлалњлЋла'
      - 'DIRECT'
    icon: 'https://www.svgrepo.com/show/452229/instagram-1.svg'

  - name: 'GOOGLE ­Ъїљ'
    type: select
    proxies:
      - 'лблЋлџлБлЕлўлЎ ­ЪќЦ'
      - '­ЪЄф­ЪЄф лАлЋлалњлЋла'
      - '­ЪЄЕ­ЪЄф лАлЋлалњлЋла'
      - 'DIRECT'
    icon: 'https://www.svgrepo.com/show/475656/google-color.svg'

  - name: 'TWITCH ­Ъј«'
    type: select
    proxies:
      - 'лблЋлџлБлЕлўлЎ ­ЪќЦ'
      - '­ЪЄф­ЪЄф лАлЋлалњлЋла'
      - '­ЪЄЕ­ЪЄф лАлЋлалњлЋла'
      - 'DIRECT'
    icon: 'https://www.svgrepo.com/show/448251/twitch.svg'

  - name: 'MICROSOFT ­ЪфЪ'
    type: select
    proxies:
      - 'лблЋлџлБлЕлўлЎ ­ЪќЦ'
      - '­ЪЄф­ЪЄф лАлЋлалњлЋла'
      - '­ЪЄЕ­ЪЄф лАлЋлалњлЋла'
      - 'DIRECT'
    icon: 'https://www.svgrepo.com/show/452062/microsoft.svg'

  - name: 'GITHUB ­ЪљЎ'
    type: select
    proxies:
      - 'лблЋлџлБлЕлўлЎ ­ЪќЦ'
      - '­ЪЄф­ЪЄф лАлЋлалњлЋла'
      - '­ЪЄЕ­ЪЄф лАлЋлалњлЋла'
      - 'DIRECT'
    icon: 'https://www.svgrepo.com/show/475654/github-color.svg'

  - name: 'TIDAL ­Ъїі'
    type: select
    proxies:
      - 'лблЋлџлБлЕлўлЎ ­ЪќЦ'
      - '­ЪЄф­ЪЄф лАлЋлалњлЋла'
      - '­ЪЄЕ­ЪЄф лАлЋлалњлЋла'
      - 'DIRECT'
    icon: 'https://www.svgrepo.com/show/504993/tidal.svg'

  - name: 'TELEGRAM Рюѕ№ИЈ'
    type: select
    proxies:
      - 'лблЋлџлБлЕлўлЎ ­ЪќЦ'
      - '­ЪЄф­ЪЄф лАлЋлалњлЋла'
      - '­ЪЄЕ­ЪЄф лАлЋлалњлЋла'
      - 'DIRECT'
    icon: 'https://www.svgrepo.com/show/354443/telegram.svg'

  - name: 'LINKEDIN ­Ъњ╝'
    type: select
    proxies:
      - 'лблЋлџлБлЕлўлЎ ­ЪќЦ'
      - '­ЪЄф­ЪЄф лАлЋлалњлЋла'
      - '­ЪЄЕ­ЪЄф лАлЋлалњлЋла'
      - 'DIRECT'
    icon: "https://www.svgrepo.com/show/448234/linkedin.svg"
    
  - name: 'FACEBOOK ­ЪЉЦ'
    type: select
    proxies:
      - 'лблЋлџлБлЕлўлЎ ­ЪќЦ'
      - '­ЪЄф­ЪЄф лАлЋлалњлЋла'
      - '­ЪЄЕ­ЪЄф лАлЋлалњлЋла'
      - 'DIRECT'
    icon: "https://www.svgrepo.com/show/475647/facebook-color.svg"

  - name: 'лблалљлцлўлџ ­ЪЄи­ЪЄ║'
    type: select
    proxies:
      - 'DIRECT'
    icon: 'https://www.svgrepo.com/show/508628/flag-ru.svg'

  - name: 'лЪлалълДлўлЎ лблалљлцлўлџ ­Ъџе'
    type: select
    proxies:
      - 'лблЋлџлБлЕлўлЎ ­ЪќЦ'
      - '­ЪЄф­ЪЄф лАлЋлалњлЋла'
      - '­ЪЄЕ­ЪЄф лАлЋлалњлЋла'
      - 'DIRECT'
    icon: 'https://www.svgrepo.com/show/293111/maps-and-flags-global.svg'

  - name: 'лЉлЏлълџлўлалълњлџлљ лалЋлџлЏлљлюлФ ­ЪЏЉ'
    type: select
    proxies:
      - 'REJECT'
    icon: 'https://www.svgrepo.com/show/300290/sign-roadblock.svg'

  - name: 'YOUTUBE РќХ№ИЈ'
    type: select
    proxies:
      - 'DIRECT'
      - 'лблЋлџлБлЕлўлЎ ­ЪќЦ'
      - '­ЪЄф­ЪЄф лАлЋлалњлЋла'
      - '­ЪЄЕ­ЪЄф лАлЋлалњлЋла'
    icon: 'https://www.svgrepo.com/show/13671/youtube.svg'

  - name: 'OPENAI ­ЪДа'
    type: select
    proxies:
      - 'лблЋлџлБлЕлўлЎ ­ЪќЦ'
      - '­ЪЄф­ЪЄф лАлЋлалњлЋла'
      - '­ЪЄЕ­ЪЄф лАлЋлалњлЋла'
      - 'DIRECT'
    icon: 'https://www.svgrepo.com/show/306500/openai.svg'

  - name: 'TIKTOK ­Ъјх'
    type: select
    proxies:
      - 'лблЋлџлБлЕлўлЎ ­ЪќЦ'
      - '­ЪЄф­ЪЄф лАлЋлалњлЋла'
      - '­ЪЄЕ­ЪЄф лАлЋлалњлЋла'
      - 'DIRECT'
    icon: 'https://www.svgrepo.com/show/303260/tiktok-logo-logo.svg'

  - name: 'STEAM ­ЪћЦ'
    type: select
    proxies:
      - 'DIRECT'
      - 'лблЋлџлБлЕлўлЎ ­ЪќЦ'
      - '­ЪЄф­ЪЄф лАлЋлалњлЋла'
      - '­ЪЄЕ­ЪЄф лАлЋлалњлЋла'
    icon: 'https://www.svgrepo.com/show/452107/steam.svg'

  - name: 'GLOBAL'
    type: select
    hidden: true
    proxies:
      - 'лблЋлџлБлЕлўлЎ ­ЪќЦ'
      - 'лблБлалЉлъ ­Ъџђ'
      - '2IP.IO ­ЪЊЇ'
      - 'лблалљлцлўлџ ­ЪЄи­ЪЄ║'
      - 'лЉлЏлълџлўлалълњлџлљ лалЋлџлЏлљлюлФ ­ЪЏЉ'
      - 'лЪлалълДлўлЎ лблалљлцлўлџ ­Ъџе'
      - 'YOUTUBE РќХ№ИЈ'
      - 'TELEGRAM Рюѕ№ИЈ'
      - 'TIKTOK ­Ъјх'
      - 'DISCORD ­Ъњг'
      - 'TWITCH ­Ъј«'
      - 'WHATSAPP ­ЪЊ▒'
      - 'INSTAGRAM ­ЪЊИ'
      - 'LINKEDIN ­Ъњ╝'
      - 'FACEBOOK ­ЪЉЦ'
      - 'GOOGLE ­Ъїљ'
      - 'OPENAI ­ЪДа'
      - 'GEMINI РЎі'
      - 'GITHUB ­ЪљЎ'
      - 'STEAM ­ЪћЦ'
      - 'MICROSOFT ­ЪфЪ'
      - 'TWITTER ­Ъљд'
      - 'NETFLIX ­Ъјг'
      - 'SPOTIFY ­ЪјД'
      - 'TIDAL ­Ъїі'

# лЪлълћлЪлўлАлџлў лЮлљ лЪлалљлњлўлЏлљ люлљлалелалБлблўлЌлљлдлўлў
rule-providers:
  HAGEZI_PRO:
    type: http
    behavior: domain
    format: mrs
    url: 'https://github.com/zxc-rv/ad-filter/releases/latest/download/adlist.mrs'
    path: ./rule-providers/hagezi_pro.mrs
    interval: 86400
  DISCORD_DOMAINS:
    type: http
    behavior: domain
    format: mrs
    url: 'https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/discord.mrs'
    path: ./rule-providers/discord_domains.mrs
    interval: 86400
  DISCORD_VOICEIPS:
    type: http
    behavior: ipcidr
    options:
      no-resolve: true
    format: mrs
    url: 'https://github.com/legiz-ru/mihomo-rule-sets/raw/main/other/discord-voice-ip-list.mrs'
    path: ./rule-providers/discord_voiceips.mrs
    interval: 86400
  TIKTOK:
    type: http
    behavior: domain
    format: mrs
    url: 'https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/tiktok.mrs'
    path: ./rule-providers/tiktok.mrs
    interval: 86400
  YOUTUBE:
    type: http
    behavior: domain
    format: mrs
    url: 'https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/youtube.mrs'
    path: ./rule-providers/youtube.mrs
    interval: 86400

# лЪлалљлњлўлЏлљ люлљлалелалБлблўлЌлљлдлўлў
rules:
  # лЉлЏлълџлўлалълњлџлљ | UDP-лблалљлцлўлџлљ лЮлљ 443 лЪлълалб лА лЮлЋ лалълАлАлўлЎлАлџлўлЦ IP
  - 'AND,((NETWORK,UDP),(DST-PORT,443),(GEOIP,!RU)),лЉлЏлълџлўлалълњлџлљ лалЋлџлЏлљлюлФ ­ЪЏЉ'
  # лЪлалълџлАлў | лўлАлџлЏл«лДлЋлЮлўлЋ | лўлЌ лЉлЏлълџлўлалълњлџлў лалЋлџлЏлљлюлФ лў лблалЋлџлЋлалълњ | лћлЏл» IPHONE LENA
  - 'SRC-IP-CIDR,192.168.100.99/32,лблЋлџлБлЕлўлЎ ­ЪќЦ'   # LENA IPHONE
  # лЉлЏлълџлўлалълњлџлљ | лалЋлџлЏлљлюлФ лў лблалЋлџлЋлалълњ
  - 'GEOSITE,CATEGORY-ADS-ALL,лЉлЏлълџлўлалълњлџлљ лалЋлџлЏлљлюлФ ­ЪЏЉ'
  - 'RULE-SET,HAGEZI_PRO,лЉлЏлълџлўлалълњлџлљ лалЋлџлЏлљлюлФ ­ЪЏЉ'
  - 'DOMAIN,tracking.ott.yandex.net,лЉлЏлълџлўлалълњлџлљ лалЋлџлЏлљлюлФ ­ЪЏЉ'
  - 'DOMAIN,egress.yandex.net,лЉлЏлълџлўлалълњлџлљ лалЋлџлЏлљлюлФ ­ЪЏЉ'
  - 'DOMAIN-SUFFIX,loveplanet.ru,REJECT'
  - 'DOMAIN-SUFFIX,mamba.ru,REJECT'
  # лЮлљлЪлал»люлБл« | лАлЏлБлќлЋлЉлЮлФлЋ лЪлалљлњлўлЏлљ
  - 'GEOIP,PRIVATE,DIRECT,no-resolve'
  # лЪлалълџлАлў | лўлАлџлЏл«лДлЋлЮлўл» лћлЏл» лалълАлАлўлЎлАлџлълЊлъ лблалљлцлўлџлљ
  - 'DOMAIN-SUFFIX,jut.su,лблЋлџлБлЕлўлЎ ­ЪќЦ'
  - 'DOMAIN-SUFFIX,jut-su.net,лблЋлџлБлЕлўлЎ ­ЪќЦ'
  # лЮлљлЪлал»люлБл« | лалълАлАлўлЎлАлџлўлЎ лблалљлцлўлџ
  - 'GEOSITE,CATEGORY-RU,лблалљлцлўлџ ­ЪЄи­ЪЄ║'
  - 'DOMAIN-SUFFIX,ru,лблалљлцлўлџ ­ЪЄи­ЪЄ║'
  - 'DOMAIN-SUFFIX,by,лблалљлцлўлџ ­ЪЄи­ЪЄ║'
  - 'DOMAIN-SUFFIX,xn--p1ai,лблалљлцлўлџ ­ЪЄи­ЪЄ║'
  - 'GEOIP,RU,лблалљлцлўлџ ­ЪЄи­ЪЄ║,no-resolve'
  - 'DOMAIN-SUFFIX,avito.ru,DIRECT'
  - 'DOMAIN-SUFFIX,avito.st,DIRECT'
  - 'DOMAIN-SUFFIX,yandex-pogoda.static-storage.net,DIRECT'
  - 'DOMAIN-SUFFIX,cdn-vk.net,DIRECT'
  - 'DOMAIN-KEYWORD,kaspersky,DIRECT'
  # лЮлљлЪлал»люлБл« | IPTV
  # PEAK TV
  - 'DOMAIN-SUFFIX,peakantikli.online,DIRECT'            # STREAM
  # LIGHT IPTV
  - 'DOMAIN-SUFFIX,ott.pp.ru,DIRECT'                     # STREAM
  # YOSSO TV
  - 'DOMAIN-SUFFIX,balelbrus.com,DIRECT'                 # STREAM
  # TV TEAM
  - 'DOMAIN-SUFFIX,team.ga,DIRECT'                       # STREAM && PICONS
  # ZABAVA
  - 'DOMAIN-SUFFIX,cdn.ngenix.net,DIRECT'                # STREAM

  # лЪлалълџлАлў лЪлалљлњлўлЏлљ | лАлЋлалњлўлАлФ лА лњлълЌлюлълќлЮлълАлблгл« лњлФлЉлълалљ лўлЌ лЪлалълџлАлў лўлЏлў лЮлљлЪлал»люлБл«
  - 'OR,((DOMAIN-SUFFIX,gql.twitch.tv),(DOMAIN-SUFFIX,usher.ttvnw.net)),TWITCH ­Ъј«'
  - 'GEOSITE,OPENAI,OPENAI ­ЪДа'
  - 'OR,((RULE-SET,DISCORD_DOMAINS),(RULE-SET,DISCORD_VOICEIPS),(AND,((DOMAIN-KEYWORD,discord),(NOT,((DOMAIN-SUFFIX,ru)))))),DISCORD ­Ъњг'
  # - 'OR,((RULE-SET,DISCORD_DOMAINS),(RULE-SET,DISCORD_VOICEIPS)),DISCORD ­Ъњг' # л┤л╗ЛЈ лИЛЂл┐ ЛЂ DISCORD_DOMAINS лИ DISCORD_VOICEIPS
  # - 'GEOSITE,DISCORD,DISCORD ­Ъњг' # л┤л╗ЛЈ лИЛЂл┐лЙл╗ЛїлилЙл▓л░лйлИЛЈ ЛЂЛѓл░лйл┤л░ЛђЛѓлйлЙл│лЙ Лёл░л╣л╗л░ geosite
  - 'RULE-SET,TIKTOK,TIKTOK ­Ъјх'
  - 'GEOSITE,TIDAL,TIDAL ­Ъїі'
  - 'GEOSITE,LINKEDIN,LINKEDIN ­Ъњ╝'
  - 'GEOSITE,FACEBOOK,FACEBOOK ­ЪЉЦ'
  - 'GEOSITE,NETFLIX,NETFLIX ­Ъјг'
  - 'GEOSITE,WHATSAPP,WHATSAPP ­ЪЊ▒'
  - 'GEOSITE,SPOTIFY,SPOTIFY ­ЪјД'
  - 'GEOSITE,INSTAGRAM,INSTAGRAM ­ЪЊИ'
  - 'GEOSITE,STEAM,STEAM ­ЪћЦ'
  #- 'GEOSITE,YOUTUBE,YOUTUBE РќХ№ИЈ'
  - 'RULE-SET,YOUTUBE,YOUTUBE РќХ№ИЈ'
  - 'GEOSITE,TWITTER,TWITTER ­Ъљд'
  - 'GEOSITE,GOOGLE,GOOGLE ­Ъїљ'
  - 'GEOSITE,GOOGLE-GEMINI,GEMINI РЎі'
  - 'GEOSITE,GITHUB,GITHUB ­ЪљЎ'
  - 'GEOSITE,MICROSOFT,MICROSOFT ­ЪфЪ'
  - 'GEOSITE,TELEGRAM,TELEGRAM Рюѕ№ИЈ'
  - 'GEOIP,TELEGRAM,TELEGRAM Рюѕ№ИЈ,no-resolve'
  # лЪлалълњлЋлалџлљ IP лљлћлалЋлАлљ | лЪлалълџлАлў лАлЋлалњлЋлалљ
  - 'DOMAIN-SUFFIX,2IP.IO,2IP.IO ­ЪЊЇ'
  # лЪлалълџлАлў лЪлалљлњлўлЏлљ | лАлЋлалњлўлАлФ лЉлЋлЌ лњлълЌлюлълќлЮлълАлблў лњлФлЉлълалљ лЪлалълџлАлў лўлЏлў лЮлљлЪлал»люлБл«
  # лЪлалълџлАлў | IPTV
  - 'DOMAIN-KEYWORD,ottbill,лблЋлџлБлЕлўлЎ ­ЪќЦ'
  - 'OR,((DOMAIN-SUFFIX,m3u.in),(DOMAIN-SUFFIX,m3u.ch),(DOMAIN-SUFFIX,m3u.work)),лблЋлџлБлЕлўлЎ ­ЪќЦ'
  - 'DOMAIN-KEYWORD,vivox,лблЋлџлБлЕлўлЎ ­ЪќЦ'
  # лЪлалълџлАлў |  RIOT GAMES / LEAGUE OF LEGENDS
  - 'IP-CIDR,104.160.128.0/19,лблЋлџлБлЕлўлЎ ­ЪќЦ,no-resolve'
  - 'IP-CIDR,185.40.64.0/22,лблЋлџлБлЕлўлЎ ­ЪќЦ,no-resolve'
  - 'IP-CIDR,151.106.240.0/20,лблЋлџлБлЕлўлЎ ­ЪќЦ,no-resolve'
  - 'IP-CIDR,192.64.168.0/21,лблЋлџлБлЕлўлЎ ­ЪќЦ,no-resolve'
  - 'IP-CIDR,162.249.72.0/21,лблЋлџлБлЕлўлЎ ­ЪќЦ,no-resolve'
  - 'IP-CIDR,103.219.128.0/22,лблЋлџлБлЕлўлЎ ­ЪќЦ,no-resolve'
  - 'IP-CIDR,103.240.224.0/22,лблЋлџлБлЕлўлЎ ­ЪќЦ,no-resolve'
  - 'IP-CIDR,43.229.64.0/22,лблЋлџлБлЕлўлЎ ­ЪќЦ,no-resolve'
  - 'IP-CIDR,45.250.208.0/22,лблЋлџлБлЕлўлЎ ­ЪќЦ,no-resolve'
  - 'IP-CIDR,45.7.36.0/22,лблЋлџлБлЕлўлЎ ­ЪќЦ,no-resolve'
  - 'IP-CIDR,138.0.12.0/23,лблЋлџлБлЕлўлЎ ­ЪќЦ,no-resolve'
  - 'IP-CIDR,151.106.250.0/23,лблЋлџлБлЕлўлЎ ­ЪќЦ,no-resolve'
  - 'IP-CIDR,192.207.0.0/24,лблЋлџлБлЕлўлЎ ­ЪќЦ,no-resolve'
  - 'IP-CIDR,104.160.141.3/32,лблЋлџлБлЕлўлЎ ­ЪќЦ,no-resolve'
  - 'IP-CIDR,104.160.142.3/32,лблЋлџлБлЕлўлЎ ­ЪќЦ,no-resolve'
  - 'IP-CIDR,104.160.131.3/32,лблЋлџлБлЕлўлЎ ­ЪќЦ,no-resolve'
  - 'IP-CIDR,104.160.156.1/32,лблЋлџлБлЕлўлЎ ­ЪќЦ,no-resolve'
  - 'IP-CIDR,104.160.152.3/32,лблЋлџлБлЕлўлЎ ­ЪќЦ,no-resolve'
  - 'IP-CIDR,185.40.67.1/32,лблЋлџлБлЕлўлЎ ­ЪќЦ,no-resolve'
  - 'IP-CIDR,104.160.131.0/24,лблЋлџлБлЕлўлЎ ­ЪќЦ,no-resolve'
  - 'IP-CIDR,172.65.212.0/24,лблЋлџлБлЕлўлЎ ­ЪќЦ,no-resolve'
  # лњлЋлАлг лЪлалълДлўлЎ лблалљлцлўлџ ­Ъџе | лА лњлълЌлюлълќлЮлълАлблгл« лњлФлЉлълалљ лўлЌ лЪлалълџлАлў лўлЏлў лЮлљлЪлал»люлБл«
  - 'MATCH,лЪлалълДлўлЎ лблалљлцлўлџ ­Ъџе'
